spring:
  application:
    name: soraka-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 80
#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
#路由
zuul:
  ignored-services: '**'
  routes:
    #微信服务中要加前缀mp http://localhost/mp/hello
    soraka-weixin: 'mp/**'
    #admin服务中要加前缀mp localhost/admin/user/info
    soraka-admin: 'admin/**'
    #auth服务中要加前缀auth 生成token:http://localhost/auth/oauth/token?client_id=soraka&client_secret=soraka&grant_type=password&username=soraka&password=123456
    #验证token:http://localhost/auth/oauth/check_token?token=
    #refresh_token: http://localhost/auth/oauth/token?grant_type=refresh_token&refresh_token=
    soraka-auth: 'auth/**'
  sensitiveHeaders: Cookie,Set-Cookie
#负载均衡
ribbon:
  ReadTimeout: 10000
#熔断
feign:
  hystrix:
      enabled: true
#认证服务器地址，通过client-id，client-secret访问认证服务器
security:
  auth:
    server: http://localhost:8005
  oauth2:
    client:
      client-id: soraka
      client-secret: soraka
    resource:
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址
#日志
logging:
  level:
    com.soraka.auth: DEBUG
    org.springframework.security: DEBUG
